### ISSUE TITLE
OrgaQuant model to quantify budding within Organoids

### ISSUE THREAD

**Issue by ryanpit98** [TKassis/OrgaQuant#1]
Dear Dr Kassis, 

I am a research student at Kings College London and I am part of the Diabetes Research Group. We use mouse and human intestinal organoids to carry out our research. Your approach to quantifying organoids is amazing and would save us a lot of time. I tried creating my own model to recognize images we took our-self(the OrgaQuant training model wouldn't recognize them) and to also quantify organoids when budding has occurred. May I share some images with you and we can possibly create a new trained model. 

Kind regards, 

Ryan Pitaluga

**Comment by TKassis** [comment]
Sure! I won't be back to campus until Jan 2nd, but I'll follow up with you then.

**Comment by ryanpit98** [comment]
Dear Dr Kassis, 

Thank you very much for getting back to me! I look forward to hearing from you. Enjoy the winter holiday. 

Kind regards, 

Ryan Pitaluga

**Comment by TKassis** [comment]
Hi Ryan, I'd be happy to create a model for you to detect budding organoids specifically. Do you have an example image I can take a look at?

**Comment by ryanpit98** [comment]
Hey Dr Kassis! That would be brilliant, thank you. 
Here are some Bright-field examples of WT Murine Small Intestinal Organoids at 4X and 10X  magnification. 
![IMG_4920](https://user-images.githubusercontent.com/57808262/73943019-f1d2f100-48e7-11ea-8942-66ad83abd372.JPG)
![IMG_5835](https://user-images.githubusercontent.com/57808262/73943027-f4354b00-48e7-11ea-9f0f-a6c17d09fed6.JPG)
![IMG_5848](https://user-images.githubusercontent.com/57808262/73943033-f5667800-48e7-11ea-8aca-f8464fa1c367.JPG)
![IMG_5892](https://user-images.githubusercontent.com/57808262/73943035-f5ff0e80-48e7-11ea-955e-b8ff1d59688a.JPG)
![IMG_6135](https://user-images.githubusercontent.com/57808262/73943039-f7303b80-48e7-11ea-9e7f-11e1bcf521de.JPG)
![IMG_6164](https://user-images.githubusercontent.com/57808262/73943042-f8616880-48e7-11ea-8a71-723f29be0dc8.JPG)

Thank you very much!

**Comment by LCapitani** [comment]
We also have some budding organoids in our lab - I'd love test the model if its been made.
Thanks!

**Comment by LCapitani** [comment]
@ryanpit98 any luck?

**Comment by ghost** [comment]
I'm a Msc student in southeast university, china, I‘m very interest in carrying on this detect project，if you’ve some dataset about organoids ,feel free to contact me. We will have further communication about this valuable thing. My email is 220201889@seu.edu.cn
