### ISSUE TITLE
Issue getting started

### ISSUE THREAD

**Issue by myavitt** [TKassis/OrgaQuant#5]
I am following the README.md file and was having issues under the "Usage" heading. When I run `streamlit run orgaquant.py`, I get the following error in Chrome: "InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version". I'm not sure what this means or how to solve it. Can you offer any advice? Thanks.

**Comment by TKassis** [comment]
Thank you for bringing this up. It either means you don't have an NVIDIA GPU, the driver hasn't been updated in a long time or that you didn't install Tensorflow correctly.
