### ISSUE TITLE
Keras requires TensorFlow 2.2 or higher error message

### ISSUE THREAD

**Issue by ioritzsb** [TKassis/OrgaQuant#7]
I got an error message when I attempted to open OrgaQuant using: streamlit run orgaquant.py
I solved the issue by installing keras==2.3.1

Installation Step 5
Code:
pip install keras-resnet==0.2.0 cython keras==2.3.1 matplotlib opencv-python progressbar2 streamlit

**Comment by jo-mueller** [comment]
If anyone stumbles upon the same issue: In my case the above configuration didn't do it, but the following did the trick:

pip install tensorflow==1.14
pip install keras==2.2.5

**Comment by 180910ldh** [comment]
> I got an error message when I attempted to open OrgaQuant using: streamlit run orgaquant.py I solved the issue by installing keras==2.3.1
> 
> Installation Step 5 Code: pip install keras-resnet==0.2.0 cython keras==2.3.1 matplotlib opencv-python progressbar2 streamlit
![1 jpg_detected](https://user-images.githubusercontent.com/43127663/136747395-cb4e63db-20b4-4dd8-83bf-a3d192f42c28.png)

Dear, I also got error and solved what you suggested. 

However, the results are not same as the user image shot, I attached the results with test images. 

How can I solve it?
