### ISSUE TITLE
Help with temporal tracking of organoids

### ISSUE THREAD

**Issue by Scrowy** [TKassis/OrgaQuant#8]
Dear Dr. Kassis,

I am a postdoctoral fellow at the University of British Columbia and wanted to thank you for this great resource! Our lab has used OrgaQuant with great success for profiling our growing organoids. We are currently tracking organoids over time to evaluate their proliferation and run into difficulties because our brightfield microscope does not have an automatic stage. Therefore we have to cycle back and forth from picture and csv file to try to match an organoid of interest over several pictures. By any chance could the program label each individual bounding box numerically which is also linked to the csv file?

Thank you in advance!

**Comment by TKassis** [comment]
Hi @Scrowy, it's definitely possible. Unfortunately, I don't have time to update this repository anymore, but I hope someone will contribute this to the code.

**Comment by LCapitani** [comment]
@Scrowy I'm a PhD student in Immunology at Cardiff University UK, and I've actually been doing the same exact thing (monitoring organoid growth over time). 

I've been meaning to try and add that feature to the fantastic orgaquant tool by TKassis :) I'll update you when I get it done!
